# Write your query or mutation here
fragment allUserField on User {
  name
  email
  isAdmin
  password_is_set
}


mutation createAdmin{
  createUser(data:{
  name:"admin",
  password:"12345678",
  email:"me2@wynwhy.com",
  isAdmin:true
}){
  name
}

}

query getAllUser($withLabel:Boolean!){
  allUsers{
    ...allUserField
    
    _label_ @include(if: $withLabel)
  
  }
}

query getCurrentUser {
  authenticatedUser {
    ...allUserField
  }
}
query getSpecificUser {
  User(where:{id:"606e8f6f53a9083afc6f54eb"}){
    ...allUserField
  }
}

query getSpecificUsers {
  allUsers(where:{isAdmin:false}){
    ...allUserField
  }
}

mutation createTestCourse{
  createCourse(data:{
    name:"testCourse",
    summary:"test course summary",
    category:C2,
    
  }){
    name
    summary
    category
  }
}


query getAllCourses {
  allCourses {
    name
    summary
    category
    content
    learningTime
   isMinimal
    coverImage{
      publicUrl
    }
    father {
      name
    }
    children {
      name
    }
  }
}



#Var
{
  "withLabel": false
}