# Write your query or mutation here
fragment allUserField on User {
  name
  email
  isAdmin
  password_is_set
}


mutation createAdmin{
  createUser(data:{
  name:"admin",
  password:"12345678",
  email:"me2@wynwhy.com",
  isAdmin:true
}){
  name
}

}

query getAllUser($withLabel:Boolean!){
  allUsers{
    ...allUserField
    
    _label_ @include(if: $withLabel)
  
  }
}

query getCurrentUser {
  authenticatedUser {
    ...allUserField
  }
}
query getSpecificUser {
  User(where:{id:"606e8f6f53a9083afc6f54eb"}){
    ...allUserField
  }
}

query getSpecificUsers {
  allUsers(where:{isAdmin:false}){
    ...allUserField
  }
}



#Var
{
  "withLabel": false
}